/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as CityRouteImport } from './routes/city'
import { Route as ClassroomRouteImport } from './routes/classroom'
import { Route as CoreRouteImport } from './routes/core'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HomeHqRouteImport } from './routes/home-hq'
import { Route as IslaRouteImport } from './routes/isla'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as PersonalizeRouteImport } from './routes/personalize'
import { Route as RealmRouteImport } from './routes/realm'
import { Route as WorldRouteImport } from './routes/world'
import { Route as WorldCentralCityRouteImport } from './routes/world/central-city'
import { Route as WorldHistoryValleyRouteImport } from './routes/world/history-valley'
import { Route as WorldInfiniteOceanRouteImport } from './routes/world/infinite-ocean'
import { Route as WorldIslaCentralRouteImport } from './routes/world/isla-central'
import { Route as WorldKnowledgeMountainsRouteImport } from './routes/world/knowledge-mountains'
import { Route as WorldSpaceZoneRouteImport } from './routes/world/space-zone'
import { Route as WorldWisdomForestRouteImport } from './routes/world/wisdom-forest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const CityRoute = CityRouteImport.update({
  id: '/city',
  path: '/city',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassroomRoute = ClassroomRouteImport.update({
  id: '/classroom',
  path: '/classroom',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreRoute = CoreRouteImport.update({
  id: '/core',
  path: '/core',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeHqRoute = HomeHqRouteImport.update({
  id: '/home-hq',
  path: '/home-hq',
  getParentRoute: () => rootRouteImport,
} as any)
const IslaRoute = IslaRouteImport.update({
  id: '/isla',
  path: '/isla',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizeRoute = PersonalizeRouteImport.update({
  id: '/personalize',
  path: '/personalize',
  getParentRoute: () => rootRouteImport,
} as any)
const RealmRoute = RealmRouteImport.update({
  id: '/realm',
  path: '/realm',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldCentralCityRoute = WorldCentralCityRouteImport.update({
  id: '/central-city',
  path: '/central-city',
  getParentRoute: () => WorldRoute,
} as any)
const WorldHistoryValleyRoute = WorldHistoryValleyRouteImport.update({
  id: '/history-valley',
  path: '/history-valley',
  getParentRoute: () => WorldRoute,
} as any)
const WorldInfiniteOceanRoute = WorldInfiniteOceanRouteImport.update({
  id: '/infinite-ocean',
  path: '/infinite-ocean',
  getParentRoute: () => WorldRoute,
} as any)
const WorldIslaCentralRoute = WorldIslaCentralRouteImport.update({
  id: '/isla-central',
  path: '/isla-central',
  getParentRoute: () => WorldRoute,
} as any)
const WorldKnowledgeMountainsRoute = WorldKnowledgeMountainsRouteImport.update({
  id: '/knowledge-mountains',
  path: '/knowledge-mountains',
  getParentRoute: () => WorldRoute,
} as any)
const WorldSpaceZoneRoute = WorldSpaceZoneRouteImport.update({
  id: '/space-zone',
  path: '/space-zone',
  getParentRoute: () => WorldRoute,
} as any)
const WorldWisdomForestRoute = WorldWisdomForestRouteImport.update({
  id: '/wisdom-forest',
  path: '/wisdom-forest',
  getParentRoute: () => WorldRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/badges': typeof BadgesRoute
  '/builder': typeof BuilderRoute
  '/city': typeof CityRoute
  '/classroom': typeof ClassroomRoute
  '/core': typeof CoreRoute
  '/home': typeof HomeRoute
  '/home-hq': typeof HomeHqRoute
  '/isla': typeof IslaRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRoute
  '/parent': typeof ParentRoute
  '/personalize': typeof PersonalizeRoute
  '/realm': typeof RealmRoute
  '/world': typeof WorldRouteWithChildren
  '/world/central-city': typeof WorldCentralCityRoute
  '/world/history-valley': typeof WorldHistoryValleyRoute
  '/world/infinite-ocean': typeof WorldInfiniteOceanRoute
  '/world/isla-central': typeof WorldIslaCentralRoute
  '/world/knowledge-mountains': typeof WorldKnowledgeMountainsRoute
  '/world/space-zone': typeof WorldSpaceZoneRoute
  '/world/wisdom-forest': typeof WorldWisdomForestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/badges': typeof BadgesRoute
  '/builder': typeof BuilderRoute
  '/city': typeof CityRoute
  '/classroom': typeof ClassroomRoute
  '/core': typeof CoreRoute
  '/home': typeof HomeRoute
  '/home-hq': typeof HomeHqRoute
  '/isla': typeof IslaRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRoute
  '/parent': typeof ParentRoute
  '/personalize': typeof PersonalizeRoute
  '/realm': typeof RealmRoute
  '/world': typeof WorldRouteWithChildren
  '/world/central-city': typeof WorldCentralCityRoute
  '/world/history-valley': typeof WorldHistoryValleyRoute
  '/world/infinite-ocean': typeof WorldInfiniteOceanRoute
  '/world/isla-central': typeof WorldIslaCentralRoute
  '/world/knowledge-mountains': typeof WorldKnowledgeMountainsRoute
  '/world/space-zone': typeof WorldSpaceZoneRoute
  '/world/wisdom-forest': typeof WorldWisdomForestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/badges': typeof BadgesRoute
  '/builder': typeof BuilderRoute
  '/city': typeof CityRoute
  '/classroom': typeof ClassroomRoute
  '/core': typeof CoreRoute
  '/home': typeof HomeRoute
  '/home-hq': typeof HomeHqRoute
  '/isla': typeof IslaRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRoute
  '/parent': typeof ParentRoute
  '/personalize': typeof PersonalizeRoute
  '/realm': typeof RealmRoute
  '/world': typeof WorldRouteWithChildren
  '/world/central-city': typeof WorldCentralCityRoute
  '/world/history-valley': typeof WorldHistoryValleyRoute
  '/world/infinite-ocean': typeof WorldInfiniteOceanRoute
  '/world/isla-central': typeof WorldIslaCentralRoute
  '/world/knowledge-mountains': typeof WorldKnowledgeMountainsRoute
  '/world/space-zone': typeof WorldSpaceZoneRoute
  '/world/wisdom-forest': typeof WorldWisdomForestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/account'
    | '/admin'
    | '/badges'
    | '/builder'
    | '/city'
    | '/classroom'
    | '/core'
    | '/home'
    | '/home-hq'
    | '/isla'
    | '/login'
    | '/missions'
    | '/parent'
    | '/personalize'
    | '/realm'
    | '/world'
    | '/world/central-city'
    | '/world/history-valley'
    | '/world/infinite-ocean'
    | '/world/isla-central'
    | '/world/knowledge-mountains'
    | '/world/space-zone'
    | '/world/wisdom-forest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/account'
    | '/admin'
    | '/badges'
    | '/builder'
    | '/city'
    | '/classroom'
    | '/core'
    | '/home'
    | '/home-hq'
    | '/isla'
    | '/login'
    | '/missions'
    | '/parent'
    | '/personalize'
    | '/realm'
    | '/world'
    | '/world/central-city'
    | '/world/history-valley'
    | '/world/infinite-ocean'
    | '/world/isla-central'
    | '/world/knowledge-mountains'
    | '/world/space-zone'
    | '/world/wisdom-forest'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/account'
    | '/admin'
    | '/badges'
    | '/builder'
    | '/city'
    | '/classroom'
    | '/core'
    | '/home'
    | '/home-hq'
    | '/isla'
    | '/login'
    | '/missions'
    | '/parent'
    | '/personalize'
    | '/realm'
    | '/world'
    | '/world/central-city'
    | '/world/history-valley'
    | '/world/infinite-ocean'
    | '/world/isla-central'
    | '/world/knowledge-mountains'
    | '/world/space-zone'
    | '/world/wisdom-forest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  BadgesRoute: typeof BadgesRoute
  BuilderRoute: typeof BuilderRoute
  CityRoute: typeof CityRoute
  ClassroomRoute: typeof ClassroomRoute
  CoreRoute: typeof CoreRoute
  HomeRoute: typeof HomeRoute
  HomeHqRoute: typeof HomeHqRoute
  IslaRoute: typeof IslaRoute
  LoginRoute: typeof LoginRoute
  MissionsRoute: typeof MissionsRoute
  ParentRoute: typeof ParentRoute
  PersonalizeRoute: typeof PersonalizeRoute
  RealmRoute: typeof RealmRoute
  WorldRoute: typeof WorldRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city': {
      id: '/city'
      path: '/city'
      fullPath: '/city'
      preLoaderRoute: typeof CityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classroom': {
      id: '/classroom'
      path: '/classroom'
      fullPath: '/classroom'
      preLoaderRoute: typeof ClassroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core': {
      id: '/core'
      path: '/core'
      fullPath: '/core'
      preLoaderRoute: typeof CoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-hq': {
      id: '/home-hq'
      path: '/home-hq'
      fullPath: '/home-hq'
      preLoaderRoute: typeof HomeHqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isla': {
      id: '/isla'
      path: '/isla'
      fullPath: '/isla'
      preLoaderRoute: typeof IslaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalize': {
      id: '/personalize'
      path: '/personalize'
      fullPath: '/personalize'
      preLoaderRoute: typeof PersonalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realm': {
      id: '/realm'
      path: '/realm'
      fullPath: '/realm'
      preLoaderRoute: typeof RealmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/central-city': {
      id: '/world/central-city'
      path: '/central-city'
      fullPath: '/world/central-city'
      preLoaderRoute: typeof WorldCentralCityRouteImport
      parentRoute: typeof WorldRoute
    }
    '/world/history-valley': {
      id: '/world/history-valley'
      path: '/history-valley'
      fullPath: '/world/history-valley'
      preLoaderRoute: typeof WorldHistoryValleyRouteImport
      parentRoute: typeof WorldRoute
    }
    '/world/infinite-ocean': {
      id: '/world/infinite-ocean'
      path: '/infinite-ocean'
      fullPath: '/world/infinite-ocean'
      preLoaderRoute: typeof WorldInfiniteOceanRouteImport
      parentRoute: typeof WorldRoute
    }
    '/world/isla-central': {
      id: '/world/isla-central'
      path: '/isla-central'
      fullPath: '/world/isla-central'
      preLoaderRoute: typeof WorldIslaCentralRouteImport
      parentRoute: typeof WorldRoute
    }
    '/world/knowledge-mountains': {
      id: '/world/knowledge-mountains'
      path: '/knowledge-mountains'
      fullPath: '/world/knowledge-mountains'
      preLoaderRoute: typeof WorldKnowledgeMountainsRouteImport
      parentRoute: typeof WorldRoute
    }
    '/world/space-zone': {
      id: '/world/space-zone'
      path: '/space-zone'
      fullPath: '/world/space-zone'
      preLoaderRoute: typeof WorldSpaceZoneRouteImport
      parentRoute: typeof WorldRoute
    }
    '/world/wisdom-forest': {
      id: '/world/wisdom-forest'
      path: '/wisdom-forest'
      fullPath: '/world/wisdom-forest'
      preLoaderRoute: typeof WorldWisdomForestRouteImport
      parentRoute: typeof WorldRoute
    }
  }
}

interface WorldRouteChildren {
  WorldCentralCityRoute: typeof WorldCentralCityRoute
  WorldHistoryValleyRoute: typeof WorldHistoryValleyRoute
  WorldInfiniteOceanRoute: typeof WorldInfiniteOceanRoute
  WorldIslaCentralRoute: typeof WorldIslaCentralRoute
  WorldKnowledgeMountainsRoute: typeof WorldKnowledgeMountainsRoute
  WorldSpaceZoneRoute: typeof WorldSpaceZoneRoute
  WorldWisdomForestRoute: typeof WorldWisdomForestRoute
}

const WorldRouteChildren: WorldRouteChildren = {
  WorldCentralCityRoute: WorldCentralCityRoute,
  WorldHistoryValleyRoute: WorldHistoryValleyRoute,
  WorldInfiniteOceanRoute: WorldInfiniteOceanRoute,
  WorldIslaCentralRoute: WorldIslaCentralRoute,
  WorldKnowledgeMountainsRoute: WorldKnowledgeMountainsRoute,
  WorldSpaceZoneRoute: WorldSpaceZoneRoute,
  WorldWisdomForestRoute: WorldWisdomForestRoute,
}

const WorldRouteWithChildren = WorldRoute._addFileChildren(WorldRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  BadgesRoute: BadgesRoute,
  BuilderRoute: BuilderRoute,
  CityRoute: CityRoute,
  ClassroomRoute: ClassroomRoute,
  CoreRoute: CoreRoute,
  HomeRoute: HomeRoute,
  HomeHqRoute: HomeHqRoute,
  IslaRoute: IslaRoute,
  LoginRoute: LoginRoute,
  MissionsRoute: MissionsRoute,
  ParentRoute: ParentRoute,
  PersonalizeRoute: PersonalizeRoute,
  RealmRoute: RealmRoute,
  WorldRoute: WorldRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
